### ISSUE TITLE
京东极速版签到报错， Cannot find module './JS_USER_AGENTS'

### ISSUE THREAD

**Issue by ma-xin** [danwangshimoluo/JdScripts#12]
```
京东极速版, 错误!
Error: Cannot find module './JS_USER_AGENTS'
Require stack:
- E:\max\tools\JD-bat\JD-script\JdScripts\jd_speed_sign.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.pjEYp (E:\max\tools\JD-bat\JD-script\JdScripts\jd_speed_sign.js:67
5:11373)
    at invite (E:\max\tools\JD-bat\JD-script\JdScripts\jd_speed_sign.js:675:1250
9)
    at jdGlobal (E:\max\tools\JD-bat\JD-script\JdScripts\jd_speed_sign.js:92:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async E:\max\tools\JD-bat\JD-script\JdScripts\jd_speed_sign.js:70:7
```
把 USER_AGENTS.js 拷贝重命名成 JS_USER_AGENTS.js，就可以运行了。

**Comment by danwangshimoluo** [comment]
fixed
